### ISSUE TITLE
Ability to only apply on certain file formats?

### ISSUE THREAD

**Issue by chenglou** [vprimachenko/Sublime-Colorcoder#11]
The plugin messes up some of my files' styling such as markdown. Since there's not much to be gained from highlighting md text (among others), I'd rather leave it as it is and only activate the plugin for .js, .css, etc.

**Comment by vprimachenko** [comment]
actually you can have it already by setting `scopes` setting to include language part of the scope, eg <code>variable.other.<strong>js</strong></code>
but i will add an `ignore_languages` option

**Comment by vprimachenko** [comment]
the `"disabled_for": []` feature is done, i need to finish `"enable_only_for":[]` and then ill push it :smile:

**Comment by chenglou** [comment]
Awesome! :+1:
