### ISSUE TITLE
Explanation of Scopes

### ISSUE THREAD

**Issue by interior-night** [vprimachenko/Sublime-Colorcoder#13]
Hi

Could you include instructions regarding usage of scopes.

Cheers.

**Comment by vprimachenko** [comment]
what exactly is unclear or in question?

**Comment by interior-night** [comment]
IN the settings, under scopes, what do "colorize", "entity.name", "support.function", "meta.function.call" and "variable.other" control? Are there any other scopes that affect the way the package works? For example, does "variable.other.js" affect the colorising despite it not being included in the default settings? Cheers.

**Comment by vprimachenko** [comment]
- said scopes are those which the plugin will colorize and 
- only those specified in settings (eg if you remove all scopes the plugin will colorize nothing, the scope has to match one single word preferably, eg `colorize` is defined as `\b\w+\b` in 'colorcoded' languages)
- `variable.other.js` will be colorized as it matches the `variable.other` scope
