### ISSUE TITLE
Crashes when trying to create new color scheme.

### ISSUE THREAD

**Issue by stathius** [vprimachenko/Sublime-Colorcoder#15]
I've tried with various different color schemes (Monokai, Blackboard etc) but every time I try run the command `Add colorcode to current color scheme` it crashes Sublime (I could c/p the long crash log if needed).
I'm using Sublime 2 on Mac OS 10.7.

I've also tried the `debug` version you provided in another ticket and the result was:

```
Traceback (most recent call last):
   File "./colorcoder.py", line 148, in panel_callback
   File "./colorcoder.py", line 159, in modify_color_scheme
AttributeError: 'module' object has no attribute 'readPlistFromBytes'
reloading /Users/kabamaru/Library/Application Support/Sublime Text 2/Packages   /User/colorcoder.sublime-settings
```

**Comment by vprimachenko** [comment]
how did you install the plugin? is seem to me you have the ST3 version running:  please check the `st2` branch

**Comment by stathius** [comment]
Before I had the plugin installed through the package manager. But when I cloned from git I didn't notice the `st2` branch, sorry.
Now it creates the color scheme but the result is the same as before. Uniform coloring. No differentiation.
![screen shot 2014-05-19 at 1 53 12](https://cloud.githubusercontent.com/assets/2035205/3013658/38402db2-df4c-11e3-81f4-80d8a57d06e1.png)

**Comment by vprimachenko** [comment]
nice, i can finally reproduce the issue, expect a fix soon

**Comment by vprimachenko** [comment]
please try [this version](https://dl.dropboxusercontent.com/u/14672987/site/colorcoder/colorcoder.py)  if it works for you ill push this upstream

**Comment by stathius** [comment]
Yep mate, it works. Thanks a lot.
It gives me a thin red line around the words (which is kinda disturbing). Is this the expected behaviour?

**Comment by vprimachenko** [comment]
> thin red line around

yeah, sadly this is a limitation of sublime 2 which i tried my best to work around but there is nothing i can do. i hope colorcoder will still be helpful
