### ISSUE TITLE
Doesn't highlight on the fly anymore

### ISSUE THREAD

**Issue by chenglou** [vprimachenko/Sublime-Colorcoder#16]
```
line 95, in on_modified_async
NameError: global name 'time' is not defined
```

ST3 on OS X.

**Comment by chenglou** [comment]
Sorry, that fixes the console error issue but the highlighting is still not done on the fly

**Comment by vprimachenko** [comment]
cant reproduce, please check by creating a new view (dont save) set the syntax to `C++ (Colorcoded)` and type some letters. You might need to delete the plugin cache first.

also check what `sublime.active_window().active_view().settings().get('colorcode',True)` returns in the console on non-updatinv views.

if you can please join the IRC channel mentiones in README so we can diagnose this faster
