### ISSUE TITLE
git master install has no default settings

### ISSUE THREAD

**Issue by michaelaye** [vprimachenko/Sublime-Colorcoder#17]
I installed colorcoder via the github master clone.
When trying to look at the available default settings, via Preferences -> Package Settings -> ColorCoder -> Setting - Default, the opened file is empty.

**Comment by vprimachenko** [comment]
wow this is rather strange

**Comment by michaelaye** [comment]
i don't understand, have u confirmed it or do you just find my report strange?

**Comment by vprimachenko** [comment]
i will set up an testing enviorment tomorrow, the "strange" means i never heard of such problem with any plugin before and am rather puzzled.

**Comment by michaelaye** [comment]
Think we can close this. it possibly has to do with the fact, that i first used PackageControl and then installed the github clone but did not use PC to remove the older version and only removed half of it in `Application\ Support`. So, the settings file is back, but I have one remaining problem: The Settings menu of ColorCoder now has every entry twice: Default 2x and User Settings 2x. :(

**Comment by vprimachenko** [comment]
did the `git clone` put the plugin in `Sublime-Colorcoder` or just `Colorcoder` folder?

**Comment by michaelaye** [comment]
Wess, your github project name is Sublime-Colorcoder, so of course the git clone created a folder called Sublime-Colorcoder. I did the `git clone` inside the `Packages` folder inside the ST3 Application Support folder on OSX. 

But interestingly, I have another new folder called Colorcoder, and that one has 2 files in it:
1. The converted Solarized (Light) (SL) (Colorcode).tmTheme
2. a file called `firstrun`.

Are you expecting things to end up in the folder `Colorcoder`? If yes, should I do the git clone into a folder called `Colorcoder` ?

**Comment by vprimachenko** [comment]
> end up in the folder Colorcoder

exactly, i guess i didnt thought that out when naming the repository, sorry for that… i will update the installation instruction in the readme.

the `colorcoder` folder you are seeing is automatically created by the plugin to store the modified color schemes (and the obligatory `firstrun` file)

**Comment by michaelaye** [comment]
Thanks! 
I copied everything over from the other folder and removed it. Now I have the menu entries only once, so all fine.
