### ISSUE TITLE
JavaScript Support

### ISSUE THREAD

**Issue by SeriousM** [vprimachenko/Sublime-Colorcoder#19]
Hi, it would be cool if we could get JS support.
Is it hard to implement?

**Comment by vprimachenko** [comment]
i have no tailored `JavaScript.tmLanguage` but `JavaScript NEXT` (from package control) works fine

**Comment by SeriousM** [comment]
I think you mean this one? https://github.com/Benvie/JavaScriptNext.tmLanguage
Does it have to be included in this package or is it enough to install it separately?

**Comment by vprimachenko** [comment]
yep that, one, separately is ok, you just have to select it in the language menu
