### ISSUE TITLE
Does not look like image. Hard to use.

### ISSUE THREAD

**Issue by roflhouse** [vprimachenko/Sublime-Colorcoder#2]
I think this looks really cool. I am very excited to try this out when it is a bit more polished. But two thing are making me not use this plugin. First the default settings do not do what your image implies and i don't know how to change the settings. Second it needs support for monokai. I know that I could probably edit some settings to get it to match more to the image but the instructions are extremely lacking. Monokai is extremely wide spread being one of the defaults. In my biased opinion it would go a long way if you got your plugin to seamlessly replace monokai. Also if you use the package control to install i don't think you can actually edit the settings seeing as ColorCoder appears under color scheme not packages in the sublime menu.

**Comment by vprimachenko** [comment]
@roflhouse could you post an image of how it looks in your installation? what version of sublime are you using? what plugins?

> don't think you can actually edit the settings seeing as ColorCoder appears under color scheme

currently the plugin offer no settings to be changed, what you see under color schemes is the modified `Obsidian` color scheme (which you need to activate to see plugins full glory)

> plugin to seamlessly replace monokai

this is not possible as plugin installation per `PackageControl` does not allow me to override files from other package (i would need to override the `Default` package), also it is never good to just override users settings (imagine you altered your theme and some plugin just overwrote the file) but provide an option - which it currently does

i will add support for `Monokai` shortly

**Comment by vprimachenko** [comment]
you can download modified `Monokai` [here](https://dl.dropboxusercontent.com/u/14672987/site/colorcoder/Monokai.tmTheme).
![proof](https://dl.dropboxusercontent.com/u/14672987/site/colorcoder/monokai.png)

 It will be bundled in next update

**Comment by roflhouse** [comment]
Very cool with the Monokai. I found out what the problem is with the colors as well. I didn't realize that there was a separate syntax c++(colorcoder) that i have to enable. Is there a way to enable it by default instead of the normal c++?

**Comment by vprimachenko** [comment]
`language menu`▶`open all with current extension as`▶`c++ (Colorcode)` or copy/hardlink `Packages/Colorcoder/C++.tmLanguage` to `Packages/C++/C++.tmLanguage`
