### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by river-of-code** [vprimachenko/Sublime-Colorcoder#20]
create an `Ruby (colorcoded).tmLanguage`

**Comment by vprimachenko** [comment]
please unpack `Ruby.tmLanguage` from `\Sublime Text 3\Packages\Ruby.sublime-package` to `\Sublime Text 3\Data\Packages\Ruby\Ruby.tmLanguage` and apply this diff

```
--- \Sublime Text 3\Data\Packages\Ruby\Ruby.tmLanguage
+++ \Sublime Text 3\Data\Packages\Ruby\Ruby.tmLanguage
@@ -2289,6 +2289,12 @@
            <key>name</key>
            <string>punctuation.section.function.ruby</string>
        </dict>
+       <dict>
+           <key>match</key>
+           <string>\b\w+\b</string>
+           <key>name</key>
+           <string>colorize.ruby</string>
+       </dict>
    </array>
    <key>repository</key>
    <dict>
```

**Comment by vprimachenko** [comment]
@the-robear was it any good?

**Comment by Vivelin** [comment]
It sure got a whole lot more colorful for me with this, at least in ST2.

**Comment by tpdorsey** [comment]
This worked great, though I extracted the default Ruby.tmLanguage file and the rest of the package contents) using PackageResourceViewer and saved the edited Ruby.tmLanguage file to ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Ruby

Thanks!
