### ISSUE TITLE
Failed to work - sublime 3 [crashed on install and on removal]

### ISSUE THREAD

**Issue by orenmizr** [vprimachenko/Sublime-Colorcoder#22]
looked promising - but did not change any colors. 
info:
i also use SublimeLinter.
Current theme - spacegray.
Current color scheme at the time of attempt - monokai gray. 

any ideas?

**Comment by Sawtaytoes** [comment]
I had a lot of crashes as well. Using the default Monokai color scheme made it stop crashing for me.
