### ISSUE TITLE
Not parsing colorscheme

### ISSUE THREAD

**Issue by coin-au-carre** [vprimachenko/Sublime-Colorcoder#23]
On Sublime text 2, I get this message once installed or launching sublimee : "Colorcoder was not able to parse the colorscheme, it is probably due some non-ascii chars in the scheme file.
We are very sorry.".
The fact is that I have tested many color schemes and even the default theme. No color scheme seems to work.

**Comment by vprimachenko** [comment]
ill look into this shortly
