### ISSUE TITLE
Python crash with ")" character.

### ISSUE THREAD

**Issue by ariamckinley** [vprimachenko/Sublime-Colorcoder#25]
I've found that when I'm using the python colorcode syntax, if I accidentally put a ) instead of an _ and save, it will lock up Sublime Text 3. It doesn't happen with a "(" or any other characters I've come across.

I'm guessing it's a problem with RegEx, I may look into it myself if I can't get a response here.

**Comment by vprimachenko** [comment]
could you post a proper code sample, as i worked on quite a few python files and never had such behaviour.

**Comment by vprimachenko** [comment]
closing as "can't reproduce"
