### ISSUE TITLE
Infinite `(Colorcoder)` renaming

### ISSUE THREAD

**Issue by Sawtaytoes** [vprimachenko/Sublime-Colorcoder#27]
Changing around my color schemas, I finally got it to stop crashing, but then it would put `(Colorcoder)` on the filenames and then put `(Colorcoder) (Colorcoder)` and then `(Colorcoder) (Colorcoder) (Colorcoder)`. The most I saw was 8 of those. I don't know what's causing this, but it's definitely causing some issues.

I couldn't tell if it did this only w/ unsupported language files or for all of them.

Package Control list:

```
{
    "auto_upgrade_last_run": null,
    "installed_packages":
    [
        "All Autocomplete",
        "ApacheConf.tmLanguage",
        "ApplySyntax",
        "AutoHotkey",
        "Autoprefixer",
        "BBCode Syntax",
        "Better CoffeeScript",
        "Blade Snippets",
        "BracketHighlighter",
        "Ciapre Color Scheme",
        "Codeivate",
        "Color Highlighter",
        "Dotfiles Syntax Highlighting",
        "EditorConfig",
        "Emmet",
        "Emmet Css Snippets",
        "FileDiffs",
        "Handlebars",
        "HTML Underscore Syntax",
        "HTML-CSS-JS Prettify",
        "Inc-Dec-Value",
        "INI",
        "Jade",
        "Jade Snippets",
        "JavaScriptNext - ES6 Syntax",
        "jQuery",
        "JS Snippets",
        "JSLint",
        "Laravel Blade Highlighter",
        "LESS",
        "Local History",
        "Lua Dev",
        "Markdown Preview",
        "Missing Palette Commands",
        "Modific",
        "Package Control",
        "Placeholders",
        "Razor",
        "Red Planet Color Scheme",
        "RevertFontSize",
        "SASS Snippets",
        "SCSS Snippets",
        "Stylus",
        "Stylus-Snippets",
        "SublimeCodeIntel",
        "SublimeLinter",
        "SublimeLinter-coffee",
        "SublimeLinter-coffeelint",
        "SublimeLinter-contrib-jslint",
        "SublimeLinter-contrib-scss-lint",
        "SublimeLinter-csslint",
        "SublimeLinter-json",
        "SublimeLinter-lua",
        "SublimeLinter-php",
        "Syntax Highlighting for Sass",
        "Syntax Matcher",
        "Tab Filter",
        "Text Pastry",
        "Theme - Phoenix",
        "Tomorrow Color Schemes",
        "UnindentPreprocessor"
    ]
}
```

**Comment by vprimachenko** [comment]
(assuming you are on Sublime 3) please try to patch the plugin like this

```
@@ -164,6 +164,9 @@
         read_original = read_original and sublime.load_settings("Preferences.sublime-settings").has("original_color_scheme")
         if read_original and sublime.load_settings("Preferences.sublime-settings").get('color_scheme').find('/Colorcoder/') == -1:
             read_original = False
+        if sublime.load_settings("Preferences.sublime-settings").get('original_color_scheme').find('/Colorcoder/') != -1:
+            print("original theme already colorcoded, abort")
+            return
         global modification_running
         if modification_running:
             return
```

yet it would be more helpful if you could make a recipe how to recreate this issue.

**Comment by Sawtaytoes** [comment]
I patched it. Working for me. Can you put this check in the live plugin as well?

The only way I know how I might recreate it is by switching color schemes while in a project with many views open at once. I work in 4 all with different syntax highlighting schemes configured.

**Comment by Sawtaytoes** [comment]
Try downloading the Color Highlighter plugin, see if that causes this to happen for you. Installed this during the same time I installed Colorcoder.

**Comment by Sawtaytoes** [comment]
Also, I noticed it's possible in the `Color Scheme` menu to select one of the Colorcoder versions. This might also cause a problem where you get `(Colorcoder)` infinites.

**Comment by vprimachenko** [comment]
> it's possible in the Color Scheme menu to select one of the Colorcoder versions

i can actually hide the modified versions but i didn't bc i think its better for user to have an item selected, so he can at least know what scheme he is using. Yet indeed i will try to improve the scheme modification logic.
