### ISSUE TITLE
Does not work with all color schemas

### ISSUE THREAD

**Issue by Sawtaytoes** [vprimachenko/Sublime-Colorcoder#28]
I receive errors when using certain color schemas such as Ciapre and Solarized.

My very amateur guess is some of the definitions you're looking for don't exist for those schemas.

**Comment by vprimachenko** [comment]
sadly i couldn't recreate this. I used the default Solarized themes and Ciapre from package control. Themes were modified as they should, both on ST3 and 2.

Please try to just open an empty sublime (empty as in no project, no workspace), load some test file (be sure to use some of the colorcoded languages), be sure to have the `auto_apply_on_scheme_change` setting in colorcoder settings on, and then change the theme. The theme should be changed and modified.

Then please check `Preferences`>`Settings - User` for values of `color_scheme` and `original_color_scheme`. Also check sublimes console (open with <kbd>CTRL</kbd><kbd>`</kbd>) for any errors.

**Comment by Sawtaytoes** [comment]
I'll make sure to do that.

It's possible I have too many custom syntax languages open causing some other issue with it too. The particular projects I worked on yesterday had JSON, CoffeeScript, JS, Sass, SCSS, Stylus, CSS, Jade, HTML, ASPX, C# all opened at the same time in Sublime Text.

Does it matter which files are currently visible instead of being hidden behind tabs? For instance, I use 4 column mode so there are 4 files opened on-screen at once.

**Comment by vprimachenko** [comment]
> Does it matter which files are currently visible instead of being hidden behind tabs?

No, the plugin only processes the view which is being edited. The amount of different languages does not have any effect.

**Comment by Sawtaytoes** [comment]
### Testing

I opened up a blank Sublime, no project or workspace, here's what I got:

```
---------------------------
Sublime Text
---------------------------
Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
---------------------------
OK   
---------------------------
```

That shows up every time I save a file.

The console shows this:

```
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Phoenix Dark.sublime-theme
error: Colorcoder was not able to parse the colorscheme
Check the console for the actual error message.
invalid literal for int() with base 16: ''
Traceback (most recent call last):
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 899, in <lambda>
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 779, in on_settings_change_view
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 899, in <lambda>
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 779, in on_settings_change_view
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 899, in <lambda>
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 779, in on_settings_change_view
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 899, in <lambda>
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 779, in on_settings_change_view
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 899, in <lambda>
  File "ColorHighlighter in C:\Users\Barkley\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 779, in on_settings_change_view
AttributeError: 'NoneType' object has no attribute 'startswith'
theme loaded
```

### User Prefs

> Note: User/Preferences.sublime-settings is currently the only file open.

```
"color_scheme": "Packages/User/CiapreBlack (SL).tmTheme",
```

There is no other var in the file as of right now.

Switching the Monokai, Sublime Text 3 stops responding. After closing and opening Sublime Text, I get a bunch of the same "can't do this" error messages. My prefs file shows:

```
"color_scheme": "Packages/User/Monokai (Colorcoded) (SL).tmTheme",
"original_color_scheme": "Packages/User/Color Highlighter/themes/Monokai.tmTheme",
```

> Note: It didn't not change the color scheme to Monokai; it's still Ciapre.

Closing the prefs and opening it again, now it's Monokai. Opening a new file and changing the syntax to CoffeeScript, it didn't have the right highlighting, but after I re-ran the `Tweak Colorcode to current color scheme`, it worked.

Accidentally switching to Ciapre (not the black one) worked smoothly. Switching to Ciapre Black brought back that same error message.

Closed and reopened Sublime Text, no error. Tweaking it for the current color scheme, now that error shows up again. Switching to Caipre (non-black), same error, but the color scheme didn't change. Closing and re-opening Sublime Text did not fix the issue.

This is what's in the pref's file:

```
"color_scheme": "Packages/User/Ciapre (SL).tmTheme",
"original_color_scheme": "Packages/User/Ciapre (Colorcoded) (SL).tmTheme",
```

Looks like all new files have the correct color scheme. To verify, I absolutely cannot get it to stop displaying error messages when using Ciapre Black, but it works using Ciapre (non-black).

Is this enough info to figure out what's going on?

**Comment by vprimachenko** [comment]
nice, thank you

the console shows errors coming from `ColorHighlighter` plugin. As both are manipulating the color scheme it could be they are interfering with each other. Please try disabling color highlighter, modifying the color scheme, setting `auto_apply_on_scheme_change` to `false` in Colorcoder options and then enable color highlighter back again. Also please upload the color schemes in question to gist or pastie so i could inspect them

**Comment by Sawtaytoes** [comment]
I agree there is interference. Currently, I've removed Color Highlighter as it's polluting my `sublime-workspace` files.

`auto_apply_on_scheme_change` helps when setting up Colorcoder. I use the `Tweak Colorcoder` option now to manually set it. Because I can select a Colorcoder-modifed scheme in the `Color Scheme` menu, this allows me to setup my color schemes ahead of time and specify them in the syntax's `sublime-settings`.

For the two theme files which error while using Colorcoder:
- [Ciapre Black](https://github.com/vinhnx/Ciapre.tmTheme/blob/master/CiapreBlack.tmTheme)
- [Red Planet](https://github.com/eliquious/Red-Planet-Theme/blob/master/Red%20Planet.tmTheme)

**Comment by dungsaga** [comment]
this problem with ColorHighlighter should be noted in wiki or readme

**Comment by vprimachenko** [comment]
was noted in bfcddb23229312ee36e79cff389510e62ae23972

**Comment by NuriddinbekWeb** [comment]
xatolik berayapti
