### ISSUE TITLE
Messes up Sublime Workspace files by adding hard color_schema values

### ISSUE THREAD

**Issue by Sawtaytoes** [vprimachenko/Sublime-Colorcoder#29]
I can't change the color schema anymore in a Sublime Text project because the `.sublime-workspace` file has a bunch of `color_schema` values defined for what looks like each file open.

These are put in only when Colorcoder is installed and references the `(Colorcoded)` version of the schema filename.

**Comment by vprimachenko** [comment]
ok, i never use workspaces. a workaround would be to set `auto_apply_on_scheme_change` to `false` in colorcoder settings, and use colorcoded themes in your workspace file. I will try to recreate this bug to make a fix.

**Comment by Sawtaytoes** [comment]
I think this might be caused by the Color Highlighter plugin as the `color_scheme` values are as such: `"color_scheme": "Packages/User/Color Highlighter/themes/CiapreBlack (SL).tmTheme",`

**Comment by Sawtaytoes** [comment]
Confirmed, this bug is false. It's a Color Highlighter bug.
