### ISSUE TITLE
White highlight for everything

### ISSUE THREAD

**Issue by sims1253** [vprimachenko/Sublime-Colorcoder#33]
No matter what color Scheme I use, I only get a white highlight for everything. Looks similar to #14. 

![sublimeerror](https://cloud.githubusercontent.com/assets/6530123/4873975/8ea56e7e-6232-11e4-9cde-2e3a871d9871.png)

**Comment by vprimachenko** [comment]
try this patch, if it helps, ill push it upstream

```
--- colorcoder.py   HEAD
+++ colorcoder.py   WORKINGDIR
@@ -167,0 +167,0 @@
-        if sublime.load_settings("Preferences.sublime-settings").get('original_color_scheme').find('/Colorcoder/') != -1:
+        if read_original and sublime.load_settings("Preferences.sublime-settings").get('original_color_scheme').find('/Colorcoder/') != -1:
```

**Comment by sims1253** [comment]
works like a charm. Thanks :)

**Comment by michaelaye** [comment]
Let us know when pushed! Great stuff.
