### ISSUE TITLE
'Error loading color scheme packages' after uninstall

### ISSUE THREAD

**Issue by loveencounterflow** [vprimachenko/Sublime-Colorcoder#39]
i tried Colorcoder which seemed like a good idea, but i found it distracting so i uninstalled it. However, even after restarting, Sublime keeps popping up annoying alert boxes with the message "Error loading color scheme Packages/Colorcoder/flow (Colorcoded).tmTheme ..." whenever i open a file. 

then, i re-installed Colorcoder in the hope i could deactivate it. but even when it is re-installed and activated (!), i _still_ get those error messages.

it gets worse: when i disable Colorcode with the Package Manager, i get this:

![screen shot 2014-11-15 at 23 28 53](https://cloud.githubusercontent.com/assets/1170565/5059558/ba600806-6d1f-11e4-8937-d1a54a991309.png)

is there a fix for this?

**Comment by caneco** [comment]
The only I found to "fix" it its to remove the "color_scheme" option in the Preferences. Then like "magic" it appears again but it stop the popups.

I hope I don't need to making a clean installation of Sublime just because this bug.

**Comment by loveencounterflow** [comment]
that's it indeed: there are two lines in the user settings file:

``` js
    "color_scheme": "Packages/Colorcoder/flow (Colorcoded).tmTheme",
    "original_color_scheme": "Packages/User/flow.tmTheme",
```

simply replacing the `color_scheme` value with its original value stopped the messages.

this certainly should be done at uninstall, so i leave this issue open.

**Comment by vprimachenko** [comment]
afaik there is not "uninstall" hook from package manager. i will note the steps needed to remove the settings in the readme. Yet the very same issue will arise when you uninstall any theme or color scheme which is currently used by sublime, so this is not an colorcoder bug

**Comment by loveencounterflow** [comment]
ok, thanks. yes, you should definitely tell users what to do, as the behavior is really annoying.
