### ISSUE TITLE
It's not working for PHP

### ISSUE THREAD

**Issue by alexdumitru89** [vprimachenko/Sublime-Colorcoder#4]
I just installed it for ST3 and it doesn't seem to be working for PHP. 

Am I doing something wrong or wasn't it designed for that ?

Thanks

**Comment by vprimachenko** [comment]
support for far more languages is coming

**Comment by vprimachenko** [comment]
@alexdumitru89 please confirm PHP support in latest version

**Comment by alexdumitru89** [comment]
It works !

Thanks a lot.
