### ISSUE TITLE
Support for PHP & JS?

### ISSUE THREAD

**Issue by khrichtchatyi** [vprimachenko/Sublime-Colorcoder#42]

**Comment by vprimachenko** [comment]
JS is supported via [`JavaScript Next` package](https://github.com/Benvie/JavaScriptNext.tmLanguage)

PHP seems to work out of the box, are you experiencing any problems?

**Comment by devnix** [comment]
I think he could refer to this. It really makes harder to read PHP code, and I cannot disable colorcoding for this language.

![image](https://cloud.githubusercontent.com/assets/1777519/21517614/b3775120-cce0-11e6-9490-57c93dc8888d.png)

![image](https://cloud.githubusercontent.com/assets/1777519/21517617/b9163cc2-cce0-11e6-8d83-59c55c22f967.png)

![image](https://cloud.githubusercontent.com/assets/1777519/21517654/02dee868-cce1-11e6-8d38-c6bb2f55e674.png)

Could be this issue be reopened?

**Comment by devnix** [comment]
#59
