### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [vprimachenko/Sublime-Colorcoder#44]
Hi. Симпатичный плагин.Идея необычная. Как по-вашему, 
можно для Synwrite так же?
https://sourceforge.net/p/synwrite/wiki/python%20API/

готов сделать donate, если поможете..

**Comment by vprimachenko** [comment]
well, i guess using `Editor.set_attr` one could make it possible. I couldn't find an API to query all identifier (or the like) from `Editor` but i guess you could easily expose it from the VCL-Component you are using, as you are already doing AST work.

**Comment by Alexey-T** [comment]
hm-what do u mean "To query all identifier (or the like) "- i have `get_attr`... so i can get all styles made in editor.

**Comment by dungsaga** [comment]
There's also LimeText, an OSS clone of Sublime Text
http://limetext.org/
It's compatible with Sublime Text plugin API.
We can try Colorcoder with this new challenger

**Comment by Alexey-T** [comment]
well- Synwrite is mine (i wanted colorcoder for mine app)
