### ISSUE TITLE
Highlight line appearance

### ISSUE THREAD

**Issue by cameronevans** [vprimachenko/Sublime-Colorcoder#47]
Might just be a result of my theme but regardless, not a big issue.
![screen shot 2015-04-01 at 10 46 48 am](https://cloud.githubusercontent.com/assets/6485269/6942406/c93055c6-d85d-11e4-818b-e86fc4d0ceb6.png)

**Comment by vprimachenko** [comment]
discussed in #32, unfixable under current api, will be fixed as soon as the api changes, its a thorn in my own eye too
