### ISSUE TITLE
Doesn't work correctly with HTML

### ISSUE THREAD

**Issue by tlindsay** [vprimachenko/Sublime-Colorcoder#5]
The plugin adds a light background color to every HTML tag.

![screen shot 2014-02-21 at 11 45 07 am](https://f.cloud.github.com/assets/2797532/2232719/12c98ce2-9b20-11e3-8481-0fe3ce27537a.jpeg)

**Comment by vprimachenko** [comment]
did you use the `Add colorcode to surrent scheme` command? what sublime version? os?

**Comment by tlindsay** [comment]
I don't believe I used that command. If so, then it was unintentional. 

I'm running v2.0.2 Build 2221 on Mac OS X 10.9.1.

Just in case I did use that command, is there a `Remove colorcode from current scheme` command?

**Comment by vprimachenko** [comment]
as the readme states "the plugin will not actually modify the scheme but create a modified copy in its own directory and apply it"

**Comment by vprimachenko** [comment]
@tlindsay so does it work now?

**Comment by tlindsay** [comment]
@vprimachenko I'm still not having any luck with it. I've been through the Readme, but I still can't quite figure out how to disable it for HTML.

**Comment by vprimachenko** [comment]
ow you want to disable it per language? that's not implemented yet, but ill code something soon

**Comment by tlindsay** [comment]
Yeah, it just doesn't seem relevant for HTML. I'll keep on eye on it, then. Thanks for the advice!
