### ISSUE TITLE
Disable a scope

### ISSUE THREAD

**Issue by ncovercash** [vprimachenko/Sublime-Colorcoder#55]
There is no functionality to disable a scope, such as

**Comment by vprimachenko** [comment]
you can specify which scopes to highlight using the `scopes` setting, like [here in the default setting](scopes)

``` json
{
    "scopes": ["colorize",
               "entity.name",
               "support.function",
               "meta.function-call",
               "variable.other"]
}
```

by omitting a value from this list you can disable highlighting of an specific scope
