### ISSUE TITLE
Missing self on method.

### ISSUE THREAD

**Issue by skuroda** [vprimachenko/Sublime-Colorcoder#6]
Guessing you meant `self.maybefixscheme()` here https://github.com/vprimachenko/Sublime-Colorcoder/blob/d84e4b17709910c36ad0dd325512ccbfa90056eb/colorcoder.py#L67. Not really worthy of a pull request, so I'll just point out the issue.

**Comment by vprimachenko** [comment]
damn missed that, thank you
