### ISSUE TITLE
Colorcoder and sublime-linter (javascript via jshint) issue

### ISSUE THREAD

**Issue by noeticpenguin** [vprimachenko/Sublime-Colorcoder#7]
Using both javascript linter, and color coder at the same time causes the plugin host to crash resulting in having to restart sublime text

**Comment by vprimachenko** [comment]
hm, i guess its a performance issue as colorcoder is kinda heavy. Do the crashes happen when starting the editor or spontaneously while working?

**Comment by noeticpenguin** [comment]
Spontaneously.

**Comment by vprimachenko** [comment]
merged into #10
